# Generated by Django 5.2.4 on 2026-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='En oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fin_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio_oferta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio oferta'),
        ),
    ]
