# Generated by Django 5.2.4 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_en_oferta_producto_fecha_fin_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo'),
        ),
    ]
