# Generated by Django 5.2.4 on 2026-05-18 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0005_pedido_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('webpay', 'Webpay Plus')], default='webpay', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('redirigido', 'Redirigido'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='iniciado', max_length=20)),
                ('buy_order', models.CharField(max_length=64, unique=True)),
                ('session_id', models.CharField(max_length=64)),
                ('token_ws', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('url_webpay', models.URLField(blank=True, default='')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=32, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
