# Generated by Django 5.2.4 on 2026-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(choices=[('webpay', 'Webpay Plus'), ('ferrecredito', 'FerreCrédito'), ('tienda', 'Pago en tienda')], default='webpay', max_length=20),
        ),
    ]
