# Generated by Django 5.2.4 on 2026-05-11 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMaestroPyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('maestro', 'Maestro'), ('pyme', 'PYME')], max_length=20)),
                ('rut', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=100)),
                ('oficio', models.CharField(blank=True, max_length=100)),
                ('nombre_empresa', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('descuento_primera_compra_usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_maestro_pyme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Maestro/PYME',
                'verbose_name_plural': 'Perfiles Maestro/PYME',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('rubro', models.CharField(max_length=100)),
                ('zona_atencion', models.CharField(max_length=150)),
                ('precio_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='maestros.perfilmaestropyme')),
            ],
            options={
                'verbose_name': 'Servicio Maestro',
                'verbose_name_plural': 'Servicios Maestro',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=30)),
                ('direccion_o_comuna', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True)),
                ('cargo_confirmacion', models.PositiveIntegerField(default=5000)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asesoria', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='maestros.serviciomaestro')),
            ],
            options={
                'verbose_name': 'Solicitud de Asesoria',
                'verbose_name_plural': 'Solicitudes de Asesoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
