# Generated by Django 5.2.4 on 2026-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='borrador', max_length=20),
        ),
    ]
