# Generated by Django 5.2.4 on 2026-05-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_en_oferta_producto_fecha_fin_oferta_and_more'),
        ('maestros', '0001_initial'),
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='solicitud_asesoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.solicitudasesoria'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tipo_linea',
            field=models.CharField(choices=[('producto', 'Producto'), ('asesoria', 'Asesoria Maestro/PYME')], default='producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
    ]
