# Generated by Django 5.2.4 on 2026-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_itempedido_descripcion_itempedido_solicitud_asesoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_puntos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='puntos_usados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
