# Generated by Django 5.2.4 on 2026-05-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_descuento_puntos_pedido_puntos_usados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
