# Generated by Django 5.2.4 on 2026-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_reservado',
            field=models.BooleanField(default=False),
        ),
    ]
