# Generated by Django 5.2.4 on 2026-05-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_usado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('cerrada', 'Cerrada')], default='activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('maestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_credito', to='maestros.perfilmaestropyme')),
            ],
            options={
                'verbose_name': 'Cuenta de Credito',
                'verbose_name_plural': 'Cuentas de Credito',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('total_cuotas', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='credito.cuentacredito')),
            ],
            options={
                'verbose_name': 'Cuota de Credito',
                'verbose_name_plural': 'Cuotas de Credito',
                'ordering': ['fecha_vencimiento', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('abono', 'Abono'), ('ajuste', 'Ajuste')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='credito.cuentacredito')),
            ],
            options={
                'verbose_name': 'Movimiento de Credito',
                'verbose_name_plural': 'Movimientos de Credito',
                'ordering': ['-creado_en'],
            },
        ),
    ]
