# Generated by Django 5.2.4 on 2026-05-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFerreCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cupo_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion_admin', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ferrecredito', to='maestros.perfilmaestropyme')),
            ],
            options={
                'verbose_name': 'Solicitud FerreCredito',
                'verbose_name_plural': 'Solicitudes FerreCredito',
                'ordering': ['-creado_en'],
            },
        ),
    ]
