# Generated by Django 5.2.4 on 2026-06-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_solicitudferrecredito'),
        ('pedidos', '0006_pedido_stock_descontado_pedido_stock_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacredito',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_credito', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='movimientocredito',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_credito', to='pedidos.pedido'),
        ),
    ]
