# Generated by Django 5.2.4 on 2026-05-11 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0004_pedido_descuento_puntos_pedido_puntos_usados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de puntos',
                'verbose_name_plural': 'Cuentas de puntos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganado', 'Ganado'), ('usado', 'Usado'), ('ajuste', 'Ajuste')], max_length=20)),
                ('puntos', models.PositiveIntegerField()),
                ('saldo_resultante', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='puntos.cuentapuntos')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de puntos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
